# Generated by Django 5.2.7 on 2025-11-13 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="entry_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
