# Generated by Django 5.2.7 on 2025-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_diaryentry_entry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="contents_predicted",
            field=models.TextField(blank=True),
        ),
    ]
