# Generated by Django 5.2.7 on 2025-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_diaryentry_contents_predicted"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="주제 문구")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "일기 주제",
                "verbose_name_plural": "일기 주제 목록",
            },
        ),
    ]
