"""
Django settings for Aiary project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ, os, json, dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# secret.json 로드
with open(BASE_DIR / "secrets.json", "r", encoding="utf-8") as f:
    SECRETS = json.load(f)


def get_secret(name, default=None):
    try:
        return SECRETS[name]
    except KeyError:
        if default is not None:
            return default
        raise RuntimeError(f"Set {name} in secrets.json")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(get_secret("DEBUG", False))

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = [get_secret("ALLOWED_HOSTS", "*")]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party
    "rest_framework",
    # Local apps
    "web", "accounts", "diary", "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Aiary.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, "templates"],    # 전역 템플릿 폴더
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Aiary.wsgi.application"
ASGI_APPLICATION = "Aiary.asgi.application"     # asgi 설정


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Step2에서 PostgreSQL로 바꿀 예정. 지금은 SQLite로 시작.
# >> PostgreSQL 변경 완료
DATABASES = {
    # "default": {
    #    "ENGINE": "django.db.backends.sqlite3",
    #    "NAME": BASE_DIR / "db.sqlite3",
    # }
    "default": dj_database_url.parse(get_secret("DATABASE_URL"))
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]         # 개발용 정적 파일 경로
STATIC_ROOT = BASE_DIR / "staticfiles"           # collectstatic 대상(배포용)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "web:home"
LOGOUT_REDIRECT_URL = "web:home"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

OPENAI_MODEL = get_secret("OPENAI_MODEL", "gpt-4.1-mini")
OPENAI_API_KEY = get_secret("OPENAI_API_KEY", None)

# 상담 프롬프트
COUNSELING_DIALOG_SYSTEM_PROMPT = get_secret(
    "COUNSELING_DIALOG_SYSTEM_PROMPT",
    default="너는 한국어로 대화하는 감정 지원 보조자이다."
)

# 일기 분석 프롬프트
COUNSELING_ANALYSIS_SYSTEM_PROMPT = get_secret(
    "COUNSELING_ANALYSIS_SYSTEM_PROMPT",
    default="너는 사용자의 일기를 분석해 요약과 감정 정리를 도와주는 보조자이다."
)


# OCR 모델 경로
OCR_MODEL_DIR = get_secret("OCR_MODEL_DIR", "./aiary_model_11_26_v3")

